### ISSUE TITLE
System.Net.WebException: Error: ConnectFailure (Connection refused)

### ISSUE THREAD

**Issue by jcyh0120** [Microsoft/mixed-reality-extension-sdk-samples#26]
I follow the readme and get this error on my oculus go.
The MRE shows hello world text but the cube is not showing.

The only different step is I type ws://192.x.x.x:3901 with my local IP.
How can I fix this problem?

**Comment by stevenvergenz** [comment]
You will also need to set the "base URL" on your app, so it knows where to look for your models (in this case the cube). If you're using a UNIX-like shell, the command is `BASE_URL=http://192.x.x.x:3901 npm start`

Try this out and see how it goes. Next time you run into an issue, post a slack message. Odds are good that someone can help you more quickly.
